[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
